params:
  problem_name: Brecket
  comment: 5 step Adamw
  method: fm_nn_heaviside
  top_opt_method: CombinedMappingDecoderSDF
  penal: 3
  shape_combination: true
  splitting: false
  merging: false
  dens_interval: 40
  dens_offset: 0
  dens_start_iter: 40
  cleaning_interval: 10
  cleaning_offset: 5
  merging_markers: [200]
  merging_adaptation: 1
  init_scale: 0.14
  axis_offset: 0.1
  init_centers_x: [0.2,  0.2, 0.2,    0.15,   0.4,  0.8,  1.25]
  init_centers_y: [1.25, 1.0, 0.3,    0.15,   0.3, 0.25, 0.2]
  # init_centers_x: [0.25, 0.25, 0.25,  0.8,  1.25]
  # init_centers_y: [1.25, 0.8,  0.25, 0.25, 0.25]
  shape_optimization_ranges: [[40, 80]]
  refactoring_markers: [42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 77, 79, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
  volfrac: 0.6
  volfrac_increment: 0.25
  volfrac_increment_marker: 10
  volfrac_increment_duration: 40
  smooth_k: 15
  N_g: 20
  N_g_x: 4
  N_g_y: 1
  max_iter: 80
  config_name: VAE_DeepSDF_quad
  # saved_model_name: frst_VAE_DeepSDF_quad_quad
  saved_model_name: frst_VAE_DeepSDF_quad_Bprec
  config_dir: ../configs/NN_sdf_experiments/final_experiments/VAEs
  input_dim: 10 # quadrangle params + 2 for point
  dataset_type: quadrangle
  merging_marker: 10
  merging_adaptation_length: 10
  ks_smooth_factor: 80
  compliance_w: 1048000000 #2
  volfrac_w: 3000000
  gaussian_overlap_w: 0
  gaussian_overlap_scale: 1.3
  rc_loss_w: 100000
  w_offsets_lr: 0.05