params:
  problem_name: MBB_beam_half
  comment: 5 step Adamw
  method: fm_nn_heaviside
  top_opt_method: CombinedMappingDecoderSDF
  penal: 3
  shape_combination: true
  splitting: false
  merging: false
  dens_interval: 40
  dens_offset: 0
  dens_start_iter: 40
  cleaning_interval: 10
  cleaning_offset: 5
  merging_markers: [200]
  merging_adaptation: 1
  shape_optimization_ranges: [[40, 150]]
  refactoring_markers: []
  volfrac: 0.6
  volfrac_increment: 0.3
  volfrac_increment_marker: 20
  volfrac_increment_duration: 40
  smooth_k: 15
  N_g: 20
  N_g_x: 4
  N_g_y: 1
  max_iter: 120
  saved_model_name: AE_DeepSDF_minMI
  config_dir: ../configs/NN_sdf_experiments/model_arch_minmi
  merging_marker: 10
  merging_adaptation_length: 10
  compliance_w: 1
  volfrac_w: 3000000
  gaussian_overlap_w: 0
  gaussian_overlap_scale: 1.3
  rc_loss_w: 100000