params:
  problem_name: Square_cantilever_beam
  comment: 5 step Adamw
  method: fm_nn_heaviside
  top_opt_method: GaussianSplattingCompliance
  penal: 3
  shape_combination: true
  splitting: false
  merging: false
  dens_interval: 40
  dens_offset: 0
  dens_start_iter: 40
  cleaning_interval: 10
  cleaning_offset: 5
  merging_markers: [200]
  merging_adaptation: 1
  axis_offset: 0.2
  init_scale: 0.2
  init_centers_x: [0.2, 0.8, 0.8]
  init_centers_y: [0.5, 0.2, 0.8]
  shape_optimization_ranges: [[40, 150]]
  refactoring_markers: [42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
  volfrac: 0.6
  volfrac_increment: 0.22
  volfrac_increment_marker: 20
  volfrac_increment_duration: 40
  smooth_k: 15
  N_g: 3
  N_g_x: 2
  N_g_y: 2
  max_iter: 80
  merging_marker: 10
  merging_adaptation_length: 10
  compliance_w: 40000 # 15
  volfrac_w: 1000000
  ks_smooth_factor: 60
  treshold: 0.5
  gaussian_overlap_w: 0
  gaussian_overlap_scale: 1.3
  rc_loss_w: 100000
  image_size: 3