model:
  type: VAE_DeepSDF
  params:
    latent_dim: 9
    hidden_dim: 128
    tau_latent_dim: 3
    tau_loss_weight: 0.01
    orthogonality_loss_weight: 0.1
    orthogonality_loss_type: None
    regularization: None
    kl_weight: 0.01
    reg_weight: 0.1

trainer:
  type: LitRecon_MINE
  params:
    learning_rate: 0.0001
    critic_learning_rate: 0.00001
    reg_weight: 0.1
    regularization: None
    warmup_steps: 1000
    info_weight: 1
