params:
  problem_name: MBB_beam_half
  comment: 5 step Adamw
  method: fm_nn_heaviside
  top_opt_method: CombinedMappingDecoderSDF
  penal: 3
  shape_combination: true
  splitting: false
  merging: false
  dens_interval: 40
  dens_offset: 0
  dens_start_iter: 40
  cleaning_interval: 10
  cleaning_offset: 5
  merging_markers: [200]
  merging_adaptation: 1
  init_scale: 0.1
  axis_offset: 0.1
  offset_grad_deceleration: 0.5
  shape_optimization_ranges: [[40, 80]]
  refactoring_markers: [42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
  volfrac: 0.6
  volfrac_increment: 0.22
  volfrac_increment_marker: 20
  volfrac_increment_duration: 40
  smooth_k: 15
  N_g: 20
  N_g_x: 4
  N_g_y: 1
  max_iter: 72
  config_name: VAE_DeepSDF_quad
  # saved_model_name: frst_VAE_DeepSDF_quad_quad
  saved_model_name: frst_VAE_DeepSDF_quad_Bprec
  config_dir: ../configs/NN_sdf_experiments/final_experiments/VAEs
  input_dim: 10 # quadrangle params + 2 for point
  dataset_type: quadrangle
  merging_marker: 10
  merging_adaptation_length: 10
  compliance_w: 1200000000 #38400 #1.2
  volfrac_w: 3000000
  gaussian_overlap_w: 0
  gaussian_overlap_scale: 1.3
  rc_loss_w: 100000