model:
  type: VAE_DeepSDF
  params:
    latent_dim: 8
    hidden_dim: 128
    tau_latent_dim: 4
    tau_loss_weight: 0.0
    orthogonality_loss_weight: 0.1
    orthogonality_loss_type: None
    regularization: None
    kl_weight: 0.0000005
    reg_weight: 0.1

trainer:
  type: LitSdfAE
  params:
    learning_rate: 0.0001
    reg_weight: 0.1
    regularization: l2
    warmup_steps: 1000
