model:
  type: AE
  params:
    latent_dim: 9
    hidden_dim: 128
    tau_latent_dim: 2
    tau_loss_weight: 0.1
    orthogonality_loss_weight: 0.1
    orthogonality_loss_type: orth_minQQ_Frobenius
    regularization: l2
    reg_weight: 0.001

trainer:
  type: LitSdfAE
  params:
    learning_rate: 0.0001
    reg_weight: 0.001
    regularization: l2
    warmup_steps: 1000