model:
  type: MMD_VAE_DeepSDF
  params:
    latent_dim: 9
    hidden_dim: 128
    tau_latent_dim: 2
    tau_loss_weight: 0.1
    orthogonality_loss_weight: 0.1
    regularization: None
    orthogonality_loss_type: orth_minQQ_Frobenius
    reg_weight: 0.001
    mmd_weight: 0.01

trainer:
  type: LitSdfAE
  params:
    learning_rate: 0.0001
    reg_weight: 0.001
    regularization: None
    warmup_steps: 1000