model:
  type: MMD_VAE
  params:
    latent_dim: 9
    hidden_dim: 128
    tau_latent_dim: 2
    tau_loss_weight: 0.1
    orthogonality_loss_weight: 0.1
    regularization: None
    reg_weight: 0.001
    mmd_weight: 0.01

trainer:
  learning_rate: 0.0001
  reg_weight: 0.001
  regularization: None
  warmup_steps: 1000